use_frameworks!

platform :ios, '9.0'

target 'Webasyst_Example' do
  pod 'Webasyst', :path => '../'

  target 'Webasyst_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
